import { VALIDATION_STAGES } from '@/constants'
import type { DashboardData } from './types'

export const dashboardMockData: DashboardData = {
  kpis: [
    {
      key: 'today',
      label: 'Importações Hoje',
      value: 24,
      icon: 'mdi-package-variant-closed',
      color: 'primary',
      trend: 'up',
      trendValue: '+12%',
    },
    {
      key: 'pending',
      label: 'Pendentes',
      value: 8,
      icon: 'mdi-clock-outline',
      color: 'warning',
      trend: 'down',
      trendValue: '-3%',
    },
    {
      key: 'in_review',
      label: 'Em Conferência',
      value: 11,
      icon: 'mdi-file-search-outline',
      color: 'info',
      trend: 'up',
      trendValue: '+5%',
    },
    {
      key: 'approved',
      label: 'Concluídas',
      value: 156,
      icon: 'mdi-check-circle-outline',
      color: 'success',
      trend: 'up',
      trendValue: '+18%',
    },
    {
      key: 'blocked',
      label: 'Bloqueadas',
      value: 4,
      icon: 'mdi-block-helper',
      color: 'error',
      trend: 'stable',
      trendValue: '0%',
    },
  ],
  monthlyChart: [
    { month: 'Jan', total: 142, approved: 128, blocked: 14 },
    { month: 'Fev', total: 158, approved: 141, blocked: 17 },
    { month: 'Mar', total: 171, approved: 155, blocked: 16 },
    { month: 'Abr', total: 189, approved: 172, blocked: 17 },
    { month: 'Mai', total: 203, approved: 186, blocked: 17 },
    { month: 'Jun', total: 218, approved: 198, blocked: 20 },
    { month: 'Jul', total: 196, approved: 178, blocked: 18 },
    { month: 'Ago', total: 224, approved: 205, blocked: 19 },
    { month: 'Set', total: 241, approved: 220, blocked: 21 },
    { month: 'Out', total: 256, approved: 234, blocked: 22 },
    { month: 'Nov', total: 268, approved: 245, blocked: 23 },
    { month: 'Dez', total: 284, approved: 261, blocked: 23 },
  ],
  timeline: [
    {
      id: '1',
      title: 'Conferência aprovada',
      description: 'DI 25/1234567-8 — Cliente LG Electronics',
      timestamp: '2026-07-01T10:32:00',
      icon: 'mdi-check-circle',
      color: 'success',
    },
    {
      id: '2',
      title: 'Bloqueio Nível 1',
      description: 'Divergência NCM — RSH30010601',
      timestamp: '2026-07-01T09:45:00',
      icon: 'mdi-alert-circle',
      color: 'error',
    },
    {
      id: '3',
      title: 'Nova importação',
      description: 'DUIMP iniciada — Samsung SDS',
      timestamp: '2026-07-01T08:15:00',
      icon: 'mdi-plus-circle',
      color: 'primary',
    },
    {
      id: '4',
      title: 'Aprovação supervisor',
      description: 'Peso bruto — Nível 2 liberado',
      timestamp: '2026-06-30T17:20:00',
      icon: 'mdi-account-check',
      color: 'warning',
    },
    {
      id: '5',
      title: 'CE Mercante validada',
      description: 'CE 162605185043815 conferida',
      timestamp: '2026-06-30T15:00:00',
      icon: 'mdi-ship-wheel',
      color: 'info',
    },
  ],
  recentOperations: [
    {
      id: 'op-001',
      reference: 'DI 25/1234567-8',
      client: 'LG Electronics',
      documentType: 'DI',
      status: 'approved',
      stage: VALIDATION_STAGES.TRIBUTACAO,
      updatedAt: '2026-07-01T10:32:00',
    },
    {
      id: 'op-002',
      reference: 'DUIMP 2026-004521',
      client: 'Samsung SDS',
      documentType: 'DUIMP',
      status: 'in_review',
      stage: VALIDATION_STAGES.NCM,
      updatedAt: '2026-07-01T09:45:00',
    },
    {
      id: 'op-003',
      reference: 'DI 25/9876543-2',
      client: 'Foxconn Brasil',
      documentType: 'DI',
      status: 'blocked',
      stage: VALIDATION_STAGES.DOCUMENTAL,
      updatedAt: '2026-07-01T08:30:00',
    },
    {
      id: 'op-004',
      reference: 'DI 25/5551234-1',
      client: 'Positivo Tecnologia',
      documentType: 'DI',
      status: 'pending',
      stage: VALIDATION_STAGES.DOCUMENTAL,
      updatedAt: '2026-07-01T07:15:00',
    },
    {
      id: 'op-005',
      reference: 'DUIMP 2026-004518',
      client: 'Multilaser',
      documentType: 'DUIMP',
      status: 'in_review',
      stage: VALIDATION_STAGES.BENEFICIOS,
      updatedAt: '2026-06-30T18:00:00',
    },
  ],
  alerts: [
    {
      id: 'alert-1',
      title: 'Risco de reenquadramento NCM',
      message: 'RSH30010601 — NCM divergente do histórico (58 importações)',
      severity: 'danger',
      timestamp: '2026-07-01T09:45:00',
    },
    {
      id: 'alert-2',
      title: 'CE Mercante pendente',
      message: 'CE 162605185043815 aguarda validação antes do registro',
      severity: 'warning',
      timestamp: '2026-07-01T08:00:00',
    },
    {
      id: 'alert-3',
      title: 'Drawback próximo do vencimento',
      message: 'Ato concessório AC 2024/00123 vence em 15 dias',
      severity: 'info',
      timestamp: '2026-06-30T16:30:00',
    },
  ],
  stageStatus: [
    { stage: VALIDATION_STAGES.DOCUMENTAL, label: 'Documental', count: 24, percentage: 100, color: 'primary' },
    { stage: VALIDATION_STAGES.BL, label: 'BL', count: 22, percentage: 92, color: 'info' },
    { stage: VALIDATION_STAGES.CE_MERCANTE, label: 'CE Mercante', count: 20, percentage: 83, color: 'info' },
    { stage: VALIDATION_STAGES.NCM, label: 'NCM', count: 18, percentage: 75, color: 'warning' },
    { stage: VALIDATION_STAGES.BENEFICIOS, label: 'Benefícios', count: 15, percentage: 63, color: 'secondary' },
    { stage: VALIDATION_STAGES.TRIBUTACAO, label: 'Tributação', count: 12, percentage: 50, color: 'success' },
  ],
  productivity: [
    { label: 'Tempo médio de conferência', value: '4.2h', icon: 'mdi-clock-fast', color: 'primary', description: '-18% vs. mês anterior' },
    { label: 'Taxa de aprovação', value: '91%', icon: 'mdi-check-decagram', color: 'success', description: '+3% vs. mês anterior' },
    { label: 'Regras executadas', value: '200', icon: 'mdi-shield-check', color: 'info', description: 'Validações automáticas ativas' },
  ],
}
