import type { ThemeDefinition } from 'vuetify'
import { DESIGN_COLORS } from '@/constants/design.constants'

export const nirronLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: DESIGN_COLORS.background,
    surface: DESIGN_COLORS.surface,
    'surface-bright': DESIGN_COLORS.surface,
    'surface-light': '#F8FBF9',
    'surface-variant': '#E8F2EC',
    'on-surface-variant': DESIGN_COLORS.onSurfaceMuted,
    primary: DESIGN_COLORS.primary,
    'primary-darken-1': DESIGN_COLORS.primaryDark,
    secondary: '#2C4A3E',
    'secondary-darken-1': '#1E3329',
    error: DESIGN_COLORS.danger,
    info: '#1565C0',
    success: DESIGN_COLORS.success,
    warning: DESIGN_COLORS.warning,
    'on-background': DESIGN_COLORS.onSurface,
    'on-surface': DESIGN_COLORS.onSurface,
    'on-primary': DESIGN_COLORS.onBrand,
    'on-secondary': DESIGN_COLORS.onBrand,
  },
  variables: {
    'border-color': DESIGN_COLORS.border,
    'border-opacity': 1,
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.68,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.06,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': DESIGN_COLORS.onSurface,
    'theme-on-kbd': DESIGN_COLORS.onBrand,
    'theme-code': '#EEF4F0',
    'theme-on-code': DESIGN_COLORS.onSurface,
  },
}

export const nirronDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#07110D',
    surface: '#102A20',
    'surface-bright': '#17382A',
    'surface-light': '#1B4331',
    'surface-variant': '#244E3A',
    'on-surface-variant': '#B6C9BE',
    primary: '#4ADE80',
    'primary-darken-1': DESIGN_COLORS.primary,
    secondary: '#A7BDB0',
    'secondary-darken-1': '#789587',
    error: '#FB7185',
    info: '#60A5FA',
    success: '#4ADE80',
    warning: '#FBBF24',
    'on-background': '#F0F7F3',
    'on-surface': '#F0F7F3',
    'on-primary': '#062D18',
    'on-secondary': '#102A20',
    'on-error': '#2D0710',
    'on-info': '#071A2D',
    'on-success': '#062D18',
    'on-warning': '#2B1D00',
  },
  variables: {
    'border-color': '#557565',
    'border-opacity': 1,
    'high-emphasis-opacity': 1,
    'medium-emphasis-opacity': 0.78,
    'disabled-opacity': 0.54,
    'idle-opacity': 0.04,
    'hover-opacity': 0.1,
    'focus-opacity': 0.18,
    'selected-opacity': 0.14,
    'activated-opacity': 0.18,
    'pressed-opacity': 0.18,
    'dragged-opacity': 0.08,
    'theme-kbd': '#F0F7F3',
    'theme-on-kbd': '#07110D',
    'theme-code': '#1B4331',
    'theme-on-code': '#F0F7F3',
  },
}

export const nirronThemes = {
  light: nirronLightTheme,
  dark: nirronDarkTheme,
}
