import type { ThemeDefinition } from 'vuetify'
import { DESIGN_COLORS } from '@/constants/design.constants'

export const nirronLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: DESIGN_COLORS.background,
    surface: DESIGN_COLORS.surface,
    'surface-bright': DESIGN_COLORS.surface,
    'surface-light': '#F8FBF9',
    'surface-variant': '#E8F2EC',
    'on-surface-variant': DESIGN_COLORS.onSurfaceMuted,
    primary: DESIGN_COLORS.primary,
    'primary-darken-1': DESIGN_COLORS.primaryDark,
    secondary: '#2C4A3E',
    'secondary-darken-1': '#1E3329',
    error: DESIGN_COLORS.danger,
    info: '#1565C0',
    success: DESIGN_COLORS.success,
    warning: DESIGN_COLORS.warning,
    'on-background': DESIGN_COLORS.onSurface,
    'on-surface': DESIGN_COLORS.onSurface,
    'on-primary': DESIGN_COLORS.onBrand,
    'on-secondary': DESIGN_COLORS.onBrand,
  },
  variables: {
    'border-color': DESIGN_COLORS.border,
    'border-opacity': 1,
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.68,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.06,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': DESIGN_COLORS.onSurface,
    'theme-on-kbd': DESIGN_COLORS.onBrand,
    'theme-code': '#EEF4F0',
    'theme-on-code': DESIGN_COLORS.onSurface,
  },
}

export const nirronDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#0A1210',
    surface: DESIGN_COLORS.brandDark,
    'surface-bright': DESIGN_COLORS.brandSurface,
    'surface-light': '#123D28',
    'surface-variant': '#1A4D32',
    'on-surface-variant': '#9CB8A8',
    primary: DESIGN_COLORS.primaryLight,
    'primary-darken-1': DESIGN_COLORS.primary,
    secondary: '#6B8F7A',
    'secondary-darken-1': '#4A6B58',
    error: '#F87171',
    info: '#60A5FA',
    success: '#34D399',
    warning: '#FBBF24',
    'on-background': '#E8F2EC',
    'on-surface': '#E8F2EC',
    'on-primary': '#0A1210',
    'on-secondary': '#0A1210',
  },
  variables: {
    'border-color': '#1A4D32',
    'border-opacity': 1,
    'high-emphasis-opacity': 0.92,
    'medium-emphasis-opacity': 0.68,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.06,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#E8F2EC',
    'theme-on-kbd': '#0A1210',
    'theme-code': '#123D28',
    'theme-on-code': '#E8F2EC',
  },
}

export const nirronThemes = {
  light: nirronLightTheme,
  dark: nirronDarkTheme,
}
